# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11d274bf3a0d89b84d30f63f8c5b50cb7bd32c0738830340b0941dcdca1fee786a1e4c2825cc4a271637da768289be92e2216918587f2f8c88a4141ea85cd44b

test:
  secret_key_base: a39651e6fabdf38444027a48785ce145c3161f584ad529ad30da7b431e7e0890a1daeb915ee3aa19b97de0db2112c226ef6b71a4c7fbd3f73be93f0fe0074d7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
